language: python

matrix:
    include:
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy3.3-5.2-alpha1
          env: TOXENV=pypy3

install:
  - "pip install tox"
  - "pip install codecov"
script: python ./.travis/run.py
after_success:
  - codecov
