language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy3

install:
  - "pip install tox"
  - "pip install codecov"
script: "tox -- -rs"
after_success:
  - codecov
