language: python

matrix:
    include:
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy3
          env: TOXENV=pypy3

install:
  - "pip install tox-travis"
  - "pip install codecov"

script: "tox -- -rs"

after_success:
  - coverage combine --append
  - coverage report -m
  - codecov
